### ISSUE TITLE
Include banked giant seaweed

### ISSUE THREAD

**Issue by TrevorMartz** [TheStonedTurtle/banked-experience#12]
Include banked giant seaweed to be made into molten glass in the crafting calculator

**Comment by TheStonedTurtle** [comment]
Converting giant seaweed into molten glass is not a fixed 1:X ratio (unless you use the seaweed on a fire for 6 soda ash, but most people won't do that).

The most common method of converting is using the [Superglass Make spell](https://oldschool.runescape.wiki/w/Superglass_Make) which is random and can vary depending on if you do the 2:12 or 3:18 method. It can be from 1.3-1.6 (7.8-9.6 molten glass per giant seaweed)

Due to this variance I have intentionally left them from the plugin, similarly farming activities that do not give a fixed rate are also excluded from the plugin.

**Comment by TrevorMartz** [comment]
I understand. If it has a solid range you could calc both the min and max. Maybe exclude it from the total(or use the minimum).

**Comment by cannonpalms** [comment]
The crafting skill menu could support several dropdown menus to achieve flexibility here, namely glass-making method (soda ash or superglass make), and if superglass make is selected, one option for inventory configuration (12:2 or 18:3). If 18:3 is selected, yet another option could be provided: pickup vs. no-pickup. Doing 12:2 is highly uncommon, however, and is pretty much trolling.

The averages are well-known for each configuration:

- sgm, 18:3, pickup -- `9.6 glass / giant seaweed`, `1.6 glass / sand`
- sgm, 18:3, no-pickup -- `9.0 glass / giant seaweed`, `1.5 glass / sand`
- sgm, 12:2 -- `8.7 glass / giant seaweed`, `1.45 glass / sand`
- soda ash -- `6 glass / giant seaweed`, `1.0 glass / sand`
- sgm, 13:13 *normal* seaweed -- `1.3 glass / seaweed`, `1.3 glass / sand`

Please let me know if you would accept a pull request to this effect and I will begin looking into it.

**Comment by TheStonedTurtle** [comment]
@cannonpalms, That won't really solve the issue of the total amount of molten glass being slightly off due to these being averages. If you use 1,000 giant seaweed with any of these methods you aren't guaranteed to get the average ratio (the sgm 18:3 pickup -> sgm 12:2). Because of this the plugin could potentially say you are going to receive a level when you won't and vice versa.

I'm not 100% against these sort of calculations there just needs to be a good visual indicator that these values are estimates and not fully accurate. I'm not sure how to go about this with the current UI setup, and would probably want that functionality on a toggle which is even more headache.

**Comment by OilyHands** [comment]
@TheStonedTurtle Might it be possible to only do the banked xp calculation for one of the less efficent configurations? And then include the caveat that it's complicated since there are a few configurations, and to only use this estimation as a ballpark figure e.g. 'you'll get at least this much molten glass/xp

**Comment by mitchhanks** [comment]
I think this would be a really nice addition to the plugin. It can only be an estimate which everyone knows, they don't have to be told that.

**Comment by TheStonedTurtle** [comment]
Due to popular demand I've began to work on a system to include RNG items, like giant seaweed.

If you know how to run a plugin-hub repo you can test the proof of concept here: <https://github.com/TheStonedTurtle/banked-experience/tree/seaweed> No eta on this feature as I am not very happy with the current UI implementation
