### ISSUE TITLE
Support for blast furnace coal rates

### ISSUE THREAD

**Issue by Budfraiz** [TheStonedTurtle/banked-experience#13]
Allow the plugin to use blast furnace coal rates for ore

**Comment by TheStonedTurtle** [comment]
I believe you are referring to the Secondaries that are displayed. Since limiting by secondaries is complicated for items like coal this information is not fully accurate anyway (like when hovering over the icons). Adding a toggle for these when you can divide the value by 2 seems unnecessary since it doesn't actually effect the experience calculation.
