### ISSUE TITLE
Bone Shards with Zealot - Banked XP is not accurate.

### ISSUE THREAD

**Issue by setter43** [TheStonedTurtle/banked-experience#147]
I appreciate the speed you rolled out the plugin update for this method, however, I think you have calculated the total number required and the use of the zealot outfit wrong.

According to the plugin I needed 120k shards from 98-99 I was already 8% of the way to 99 and I used my 126k shards.
Using my calculations I needed close to 240k ( Can't remember if this was with Zealot or not).

I think the issue is:
On click 100 bone shards are used, and on average we save 5% of that 100, (Basically each time 5+ shards are always saved)
Rather than 5% of the time we save the 100 shards.
I think your plugin calculates each 100 we save 5% of the time.

Hopefully, this makes sense

![2024-04-14_12-25-28](https://github.com/TheStonedTurtle/banked-experience/assets/49942725/cda976c9-f7a6-4ef4-8c90-a9f688797de9)
![2024-04-14_12-25-21](https://github.com/TheStonedTurtle/banked-experience/assets/49942725/7bd4dbaa-6c35-4412-8cd5-c1d10da2fbb2)
![2024-04-14_12-25-02](https://github.com/TheStonedTurtle/banked-experience/assets/49942725/d2b3a0e9-d571-4c92-9714-aa6dc3342aec)
![2024-04-14_12-24-50](https://github.com/TheStonedTurtle/banked-experience/assets/49942725/e4220af1-9de5-44d6-8e2e-6396c86a944f)
![2024-04-14_12-24-35](https://github.com/TheStonedTurtle/banked-experience/assets/49942725/f49a970f-11ad-4071-8f65-087c077cb6e2)

**Comment by setter43** [comment]
To add I am wearing full zealot

**Comment by TheStonedTurtle** [comment]
> I think your plugin calculates each 100 we save 5% of the time.

Maybe I just don't understand the math here but if you save 100 5% of the time that means you have a 1/20 chance of saving 100.

If you save 5% per action after 20 actions you should also save 100?

**Comment by TheStonedTurtle** [comment]
Here's the formula it's using for this calculation, lets walk through this to see if you can find an issue:

The calculated `XP per Bone Shard` = `ActionXP/ConsumptionChance` where:
`ActionXP` is set for each bone shard by the activity (either `5` or `6` depending on wine type)
The `ConsumptionChance` is calculated as: `(1 - ChanceToSave) * ChanceToConsume`

The `ChanceToSave` is for Additive effects, such as the Wildy Altar.
The `ChanceToConsume` is for things that stack multiplicatively after the `ChanceToSave` is applied, which is done so Zealot Robes work with the Wildy Altar. The number used in the calculation is also reversed due to its multiplicative nature. This means if you have a 5% chance to save via the robes you also have a 95% chance to consume them. We use the Consumption number because
> Zealot's robes are ... totalling 5% with the full set equipped. This bonus stacks multiplicatively with the bone-saving effect of the [Chaos Temple](https://oldschool.runescape.wiki/w/Chaos_Temple_(hut)) altar.[[1]](https://oldschool.runescape.wiki/w/Zealot%27s_robes#cite_note-1)

Source: https://oldschool.runescape.wiki/w/Zealot%27s_robes

The only two `Consumption Modifiers` that exist, currently, are the Wildy Altar & Zealots, and only Zealots are applicable here.

So if you only have all the Zealots Robes enabled this makes the `ConsumptionChance` = `(1 - 0) * .95` which is `.95`. In this case there is no difference between if we calculated it as `ChanceToSave` or `ChanceToConsume` so that above is sorta irrelevant.

So now we have `ActionXP/.95` as our formula where `ActionXP` is either `5` or `6`.
For `5/.95` we get `5.263...`
For `6/.95` we get `6.315...`

We take this value and round using the `HALF_UP` method to the Hundredths place, making the values `5.26` and `6.32` respectively, which is what is displaying in the plugin: 
![image](https://github.com/TheStonedTurtle/banked-experience/assets/29030969/41c30838-508f-487a-81f1-57cfd5a550bf)
![image](https://github.com/TheStonedTurtle/banked-experience/assets/29030969/85294ddb-f8ce-4878-9701-97db12e836a0)

**Comment by TheStonedTurtle** [comment]
Also your note of:
> According to the plugin I needed 120k shards from 98-99 I was already 8% of the way to 99 and I used my 126k shards.

This plugin doesn't show what you need for a specific level range, it only shows what you have banked between all your items in the bank. You need to right-click ignore items if you want it to be based off just the shards.

120,000 shards at `6.23`xp each, which is using `Sunfire Wine` with all zealot robes, is only `747,600` experience. Without photo evidence I don't believe that the plugin was showing you that 120,000 shards was enough for 99. That calculation would need to be nearly doubled, and the calculation matches exactly what I'm saying based off the images in my previous comments.
