### ISSUE TITLE
Not updating construction xp with carpenter's outfit modifier when then activity is mahogany homes

### ISSUE THREAD

**Issue by TheAngusBurger** [TheStonedTurtle/banked-experience#53]
As title says.

When selecting the carpenters outfit modifier, it only updates the 'total banked xp' when the activity 'products' is selected. When the activity 'mahogany homes' is selected, the carpenters outfit does not affect the banked xp.

**Comment by TheStonedTurtle** [comment]
This was done intentionally as the experience awarded at the end of the contract does not get the boost from the outfit, which is a majority of the exp you get from the activity and it makes the average xp/plank harder to calculate for the outfit.

![image](https://user-images.githubusercontent.com/29030969/129126876-234437f9-3412-4891-b9fe-b08e4a49f93a.png)

Applying the 2.5% set bonus to the first values does not achieve the second value, and based on my math the second values range from .7% to 1% better than without the entire set.

Because of the range of values I don't see a way to implement the outfit correctly for each individual piece that is selected, and having it only work when all pieces are selected does not seem like a good design.

**Comment by aes5521** [comment]
@TheStonedTurtle It may be helpful to add a quick tooltip about that if you have any interest - if anything just to make it so you don't get people posting duplicate requests on this topic
