### ISSUE TITLE
Interface tiles same size

### ISSUE THREAD

**Issue by Wiebrendh** [TheStonedTurtle/banked-experience#7]
For example: when selecting teak planks or mahogany planks. The tiles move a bit since teak planks have the option between reg usage and the cape racks. Would be nice if those panels are all the same size.

**Comment by TheStonedTurtle** [comment]
This has been fixed in v1.2, which <a href="https://github.com/runelite/plugin-hub/pull/38" target="_blank">has been submitted</a> to the plugin hub about 30seconds before you posted this issue (What are the odds? lol)

![xhqt3eR8ZN](https://user-images.githubusercontent.com/29030969/71528560-3bfe9680-2895-11ea-996a-425a32e75bfb.gif)

**Comment by Wiebrendh** [comment]
Love the timing. Thanks mate, great plugin!
