### ISSUE TITLE
Contradicting secondary logic for staminas (with suggested solution)

### ISSUE THREAD

**Issue by lukaschristensson** [TheStonedTurtle/banked-experience#76]
As it stands right now, Super Energy (1) is classified as the secondary for Amylase crystal. I think it should be the other way around, with amalyze being the secondary ingredient (as far as I can tell, would be in line with what other recipes suggest), which should also be combined with a proper calculations for "grimy avantoe -> staminas" in the xp calc. I understand how it would be quite annoying to calculate the amount of doses every avantoe potion (unf) gives given the necklace of chemistry but it could be solved by adding a recipe like either using avantoe potion (unf) to make "Super energy potion" or "[x1.05] Super energy potion (necklace of chemistry)", kind of like what you do with soda ash and molten glass.

**Comment by TheStonedTurtle** [comment]
Since I mainly play on an ironman I considered the harder to get resource the primary item, and in my opinion amalyze crystals are the harder to get item. Most ironmen don't grind out a high level of agility until the late game so the crystals are generally the limiting factor. Since limiting by secondaries isn't a feasible thing to implement due to items like coal being used in multiple activities I think it's fine the way it is.

**Comment by lukaschristensson** [comment]
As a fellow ironman I strongly disagree but I do respect your decision. (this could maybe be a tickbox too as i know most people in my ironman clan finds it to be a problem when using the plugin)
